version: '3'
services:
  web:
    container_name: landingpage
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    env_file: ./backend/.env
    environment:
      NODE_ENV: production