version: "3"

services:
  frontend:
    container_name: landingpage
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./config/frontend.dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - staticfiles:/app/staticfiles
      - ./config/nginx/production:/etc/nginx/conf.d
      - ./config/nginx/certbot/conf:/etc/letsencrypt
      - ./config/nginx/certbot/www:/var/www/certbot
  
  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./config/nginx/certbot/conf:/etc/letsencrypt
      - ./config/nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  staticfiles: